AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - Gemfile
  - Rakefile
  - spec/**/*
  - vendor/**/*
  DisplayCopNames: true
LineLength:
  Enabled: false
DoubleNegation:
  Enabled: false
Documentation:
  Enabled: false
Style/PredicateName:
  Enabled: false
MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 33
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 11